// hooks/useAuthApi.js
import { useAxios } from '../hooks/useAxios';

const useAuthApi = () => {
  const axiosInstance = useAxios();

  const login = async ({ username, password }) => {
    try {
      const response = await axiosInstance.post('/user/login', { username, password });
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al iniciar sesi칩n';
    }
  };

  const registerMail = async (user) => {
    try {
      console.log('Usuario registrado:', user);
      const response = await axiosInstance.post('/user/register/mail', user);
      return response.data;
    } catch (error) {
      console.log('ESTOY ACA ERROR CACA:', user);
      throw error.response?.data?.message || 'Error al enviar correo de registro';
    }
  };

  const register = async ({ username, code }) => {
    try {
      const response = await axiosInstance.post('/user/register', { username, code });
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al registrar usuario';
    }
  };

  const recoverMail = async (username) => {
    try {
      const response = await axiosInstance.post('/user/recover/mail', username, {
        headers: { 'Content-Type': 'application/json' },
        responseType: 'text',
      });
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al enviar correo de recuperaci칩n';
    }
  };

  const recover = async ({ username, code }) => {
    try {
      const response = await axiosInstance.post('/user/recover', { username, code });
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al recuperar contrase침a';
    }
  };

  const updatePassword = async ({ username, password }) => {
    try {
      const response = await axiosInstance.post('/user/newPassword', { username, password });
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al establecer nueva contrase침a';
    }
  };

  const getProfile = async () => {
    try {
      const response = await axiosInstance.get('/user/profile');
      return response.data;
    } catch (error) {
      throw error.response?.data?.message || 'Error al obtener perfil';
    }
  };

  return {
    login,
    registerMail,
    register,
    recoverMail,
    recover,
    updatePassword,
    getProfile,
  };
};

export default useAuthApi;
